### ISSUE TITLE
Power sensor not coming up in Energy consumption 

### ISSUE THREAD

**Issue by mad2691** [david-collett/reclaimenergy#3]
I wanted to add reclaim in to my consumption dashboard but for some reason it is not available

**Comment by david-collett** [comment]
The reclaim only reports power (kw), not energy (kwh).
As per the readme, this can be accomplished using a home assistant helper (settings / devices and services /helpers) to create an energy sensor from the power sensor:

To integrate the Power sensor into the energy dashboard, use the "Integral Sensor" helper to create a Left Riemann sum sensor based on the reclaim power sensor, this will produce accumulating KWh for use in energy dashboard.
